export PATH=$HOME/.local/bin:$HOME/npm/bin:$PATH
export GOPATH=$HOME/Code
export GOPROXY=direct
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOPATH/bin/go/bin
export PATH=$PATH:$HOME/.nvm
export GOFLAGS=-mod=mod
export GO111MODULE=on

export NVM_DIR=~/.nvm
 [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
export PATH=$PATH:/usr/local/bin/flutter/bin

 #Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

source $HOME/.config/base16-shell/scripts/base16-materia.sh
ZSH_THEME="clean"

source $ZSH/oh-my-zsh.sh

plugins=(git composer symfony2 docker aws npm node)


# Docker
alias dps='docker ps --format="table {{ .ID }}\t{{ .Names }}\t{{ .Image }}\t{{ .Status }}\t{{ .Ports }}\t{{ .Command }}"'
alias dc='docker-compose'
alias dcps='docker-compose ps'

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export dev=$GOPATH/src
