---
- name: Ensure ZSH Is Set up
  hosts: localhost
  roles:
    - zsh
- name: Create a new machine
  hosts: localhost
  roles:
    - common
    - git
    - vscode
    - go
    - docker
    - slack
    - node
    - flutter
    - signal