- name: Ensure Java is Installed
  apt:
    update_cache: yes
    pkg:
      - default-jdk
      - default-jre
    state: present
  become: yes
- name: Download tar
  get_url:
    dest: /tmp/flutter # required. Absolute path of where to download the file to.,If C(dest) is a directory, either the server provided filename or, if none provided, the base name of the URL on the remote server will be used. If a directory, C(force) has no effect.,If C(dest) is a directory, the file will always be downloaded (regardless of the C(force) option), but replaced only if the contents changed..
    url: https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_1.20.3-stable.tar.xz # required. HTTP, HTTPS, or FTP URL in the form (http|https|ftp)://[user[:pass]]@host.domain[:port]/path
  become: yes
- name: Extract/Install
  become: yes
  unarchive:
    src: /tmp/flutter # required. If C(remote_src=no) (default), local path to archive file to copy to the target server; can be absolute or relative. If C(remote_src=yes), path on the target server to existing archive file to unpack.,If C(remote_src=yes) and C(src) contains C(://), the remote machine will download the file from the URL first. (version_added 2.0). This is only for simple cases, for full download support use the M(get_url) module.
    dest: "/usr/local/bin" # required. Remote absolute path where the archive should be unpacked.
    owner: "{{ lookup('env', 'USER') }}" # not required. Name of the user that should own the file/directory, as would be fed to I(chown).
    group: "{{ lookup('env', 'USER') }}"
- name: Precache Dependencies
  become: yes
  shell: flutter precache
      