- name: Remove old packages
  apt:
    pkg:
      - docker 
      - docker-engine 
      - docker.io 
      - containerd 
      - runc
    state: absent
  become: yes
- name: Install pre-requisites
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
  become: yes
- name: Add key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add repository
  become: yes
  apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present
- name: Install Docker
  become: yes
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
- name: Add Docker Group
  group:
    name: docker
    state: present
- name: "Add {{ lookup('env', 'USER') }} to docker group"
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes
- name: Install Docker Compose
  become: yes
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
    owner: "{{ lookup('env', 'USER') }}"